import pandas as pd
import json
import seaborn as sns
import matplotlib.pyplot as plt
import os

# ==========================================
# 1. CONFIGURATION
# ==========================================
# Map the labels you want on the X-axis to the JSON files generated by evaluate_top_k.py
"""file_map = {
    "Transolver": r"/home/sushil/PressNet/_Nas_Mount/ank-server1/prj_accelerated_physics/prj_pressnet/Training_data_Susil/transolver/E1_C/Transolver_Slice64/New_Combined/Inference_Retrain_OOD_Unseen/evaluation_top_10pct_metrics/top_10pct_evaluation_summary.json",
    "Dilated DGCNN": r"/home/sushil/PressNet/_Nas_Mount/ank-server1/prj_accelerated_physics/prj_pressnet/Training_data_Susil/dilated/1_Inference_new/Dilated_Inference_OOD_Unseen/evaluation_top_10pct_metrics/top_10pct_evaluation_summary.json",
    "GCN": r"/home/sushil/PressNet/_Nas_Mount/ank-server1/prj_accelerated_physics/prj_pressnet/Training_data_Susil/gcn/Inference_new/GCN_Inference_OOD_Unseen/evaluation_top_10pct_metrics/top_10pct_evaluation_summary.json",
    "MeshgraphNet": r"/home/sushil/PressNet/_Nas_Mount/ank-server1/prj_accelerated_physics/prj_pressnet/Training_data_Susil/mgn/Combined_Inference/Infer_Unseen_test/evaluation_top_10pct_metrics/top_10pct_evaluation_summary.json",
    "DGCNN": r"/home/sushil/PressNet/_Nas_Mount/ank-server1/prj_accelerated_physics/prj_pressnet/Training_data_Susil/reg/Inference_new/DGCNN_Inference_OOD_Unseen/evaluation_top_10pct_metrics/top_10pct_evaluation_summary.json"
}"""

file_map = {
    "Transolver": r"/home/sushil/PressNet/_Nas_Mount/ank-server1/prj_accelerated_physics/prj_pressnet/Training_data_Susil/transolver/E1_C/Transolver_Slice64/New_Combined/Inference_Retrain_Extrapolation/evaluation_top_10pct_metrics/top_10pct_evaluation_summary.json",
    "Dilated DGCNN": r"/home/sushil/PressNet/_Nas_Mount/ank-server1/prj_accelerated_physics/prj_pressnet/Training_data_Susil/dilated/1_Inference_new/Dilated_Inference_Extrapolation/evaluation_top_10pct_metrics/top_10pct_evaluation_summary.json",
    "GCN": r"/home/sushil/PressNet/_Nas_Mount/ank-server1/prj_accelerated_physics/prj_pressnet/Training_data_Susil/gcn/Inference_new/GCN_Inference_Extrapolation/evaluation_top_10pct_metrics/top_10pct_evaluation_summary.json",
    "MeshgraphNet": r"/home/sushil/PressNet/_Nas_Mount/ank-server1/prj_accelerated_physics/prj_pressnet/Training_data_Susil/mgn/Combined_Inference/Infer_Extrapolation/evaluation_top_10pct_metrics/top_10pct_evaluation_summary.json",
    "Reg_DGCNN": r"/home/sushil/PressNet/_Nas_Mount/ank-server1/prj_accelerated_physics/prj_pressnet/Training_data_Susil/reg/Inference_new/DGCNN_Inference_Extrapolation/evaluation_top_10pct_metrics/top_10pct_evaluation_summary.json"
}


METRIC_CHOICE = "top_10pct_rmse" 
PERCENTILE_LABEL = "Top 10%"
SAVE_FILENAME = "Top_10Pct_RMSE_ExtrapolationSet.png"

# ==========================================
# 2. DATA LOADING & PROCESSING
# ==========================================
def load_and_process_data(paths, metric_name):
    processed_records = []
    for label, path in paths.items():
        if not os.path.exists(path):
            print(f"Warning: File not found for {label} at {path}")
            continue
        with open(path, 'r') as f:
            data = json.load(f)
            # Parse the new JSON structure
            for traj in data.get("trajectories", []):
                for metric in traj.get("metrics", []):
                    qty = metric.get("quantity")
                    val = metric.get(metric_name)
                    
                    if val is not None:
                        processed_records.append({
                            "Param": label,
                            "Trajectory": traj.get("trajectory_index"),
                            "Qty": "Stress" if "stress" in qty.lower() else "Y-Disp",
                            "Error_Val": val
                        })
    return pd.DataFrame(processed_records)

# ==========================================
# 3. DATA PREPARATION & OUTLIER LOGIC
# ==========================================
df = load_and_process_data(file_map, METRIC_CHOICE)

if df.empty:
    print("❌ Error: No data was parsed. Check your JSON keys and file paths.")
else:
    # Use Categorical to maintain the exact order from file_map keys
    df['Param'] = pd.Categorical(df['Param'], categories=list(file_map.keys()), ordered=True)
    df = df.sort_values("Param")

    # Define dynamic Y-limits PER QUANTITY
    y_limits = {}
    for qty in df["Qty"].unique():
        qty_df = df[df["Qty"] == qty]
        y_limits[qty] = qty_df["Error_Val"].quantile(0.96) * 1.6

    # Calculate Outliers for the terminal report
    def calculate_outliers(group):
        q1 = group["Error_Val"].quantile(0.25)
        q3 = group["Error_Val"].quantile(0.75)
        iqr = q3 - q1
        upper_whisker = q3 + 1.5 * iqr
        
        qty_name = group["Qty"].iloc[0]
        y_limit_for_qty = y_limits[qty_name]
        
        total_outliers = group[group["Error_Val"] > upper_whisker].shape[0]
        hidden_outliers = group[group["Error_Val"] > y_limit_for_qty].shape[0]
        
        return pd.Series({
            "Total_Outliers": total_outliers,
            "Hidden_by_Limit": hidden_outliers,
            "Max_Error": round(group["Error_Val"].max(), 4)
        })

    outlier_summary = df.groupby(['Param', 'Qty'], observed=True).apply(calculate_outliers).reset_index()

    print("\n" + "="*85)
    print(f"STATISTICAL SUMMARY (Metric: {METRIC_CHOICE.upper()})")
    for qty, lim in y_limits.items():
        print(f"Current Y-Axis Display Limit for {qty}: {lim:.2f}")
    print("="*85)
    print(outlier_summary.to_string(index=False))
    print("-" * 85)
    print(f"TOTAL HIDDEN DATA POINTS ACROSS ALL GROUPS: {int(outlier_summary['Hidden_by_Limit'].sum())}")
    print("="*85 + "\n")

    # ==========================================
    # 4. PLOTTING
    # ==========================================
    # Journal-style formatting
    sns.set_context("paper", font_scale=1.2)
    sns.set_style("ticks")

    quantities = df["Qty"].unique()
    
    # REDUCED overall figure width (from 5.0 to 4.0 per subplot) to decrease the gap between boxes
    fig, axes = plt.subplots(1, len(quantities), figsize=(4.0 * len(quantities), 5.0))
    if len(quantities) == 1: axes = [axes]

    for ax, qty in zip(axes, quantities):
        subset = df[df["Qty"] == qty]

        bp = sns.boxplot(
            data=subset, 
            x="Param", 
            y="Error_Val", 
            palette="Set1", 
            width=0.35,      # REDUCED box width from 0.5 to 0.35 to make them slimmer
            linewidth=1.0,   # Slimmer lines for a cleaner professional look
            fliersize=2.0,   
            showmeans=True,
            meanprops={"marker":"^", "markerfacecolor":"white", "markeredgecolor":"black", "markersize": 5.5},
            ax=ax
        )

        # Apply the adaptive Y-axis limit for this specific quantity
        ax.set_ylim(0, y_limits[qty])

        # --- Styling ---
        sns.despine(ax=ax) 
        
        # Add a subtle horizontal grid behind the boxes for easier reading
        ax.yaxis.grid(True, linestyle='--', alpha=0.6)
        ax.set_axisbelow(True)
        
        ax.set_title(f"{PERCENTILE_LABEL} Extreme Regions: {qty}", fontweight='bold', pad=10)
        ax.set_ylabel(f"RMSE [{qty}]", fontweight='bold')
        ax.set_xlabel("Model Architecture", fontweight='bold')
        
        # PERFECTED LABEL ROTATION: ha='right' and rotation_mode='anchor' aligns them cleanly
        ax.set_xticks(range(len(file_map)))
        ax.set_xticklabels(list(file_map.keys()), rotation=30, ha='right', rotation_mode='anchor', fontsize=10)

    # Final Adjustment and Save
    plt.tight_layout()
    plt.savefig(SAVE_FILENAME, dpi=600, bbox_inches='tight')
    print(f"✅ Success: Journal-ready plot saved as {SAVE_FILENAME}")